const colors = {
  light: {
    text: "#2D2D2D",
    tint: "#FF8B6A",
    background: "#F7F3EF",
    foreground: "#2D2D2D",
    card: "#FFFAF4",
    cardForeground: "#2D2D2D",
    primary: "#FF8B6A",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE6DE",
    secondaryForeground: "#2D2D2D",
    muted: "#EDE6DE",
    mutedForeground: "#6B6B6B",
    accent: "#8B68FF",
    accentForeground: "#FFFFFF",
    destructive: "#ef4444",
    destructiveForeground: "#FFFFFF",
    border: "#EDE6DE",
    input: "#EDE6DE",
    peach: "#FF8B6A",
    peachLight: "#FFF0EA",
    peachMid: "#FFD6C8",
    mint: "#3DB884",
    mintLight: "#E8F8F1",
    mintMid: "#C8F0E0",
    lavender: "#8B68FF",
    lavLight: "#F0ECFF",
    lavMid: "#E4D9FF",
    lemon: "#F5C400",
    lemonLight: "#FFFBE0",
    sky: "#3DA0F5",
    skyLight: "#EBF5FF",
    cream: "#FFFAF4",
    dark: "#2D2D2D",
  },
  radius: 16,
};

export default colors;
